# Generated by Django 6.0.7 on 2026-07-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('teacher', 'Teacher'), ('super_admin', 'Super Admin')], max_length=20),
        ),
    ]
