# Generated by Django 6.0.7 on 2026-07-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institute_address_institute_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institute',
            name='trial_ends_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
